"""Render reviewed guide content and the local-only size calculator into static pages."""
from pathlib import Path
import re,json,html,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
BASE='https://usephotoprint.com/'
DATE='2026-10-03'
APPLE='https://support.apple.com/en-us/109349'
ADOBE='https://helpx.adobe.com/acrobat/desktop/print-documents/set-up-and-print-pdfs/page-size.html'
source=(ROOT/'print-2x2-photos-iphone.html').read_text()
header=re.search(r'<header.*?</header>',source,re.S).group()
footer=re.search(r'<footer.*?</footer>',source,re.S).group()
def page(slug,title,description,body,kind='Article',script=''):
 url=BASE+slug+'.html'
 data={'@context':'https://schema.org','@type':kind,'headline':title,'name':title,'description':description,'url':url,'datePublished':DATE,'dateModified':DATE,'author':{'@type':'Person','name':'Mohamed Elatabany','url':BASE+'about.html'},'mainEntityOfPage':url}
 cta=f'<aside class="guide-cta"><h2>Make the sheet on your iPhone.</h2><p>Photo Print has exact sizes, sheet previews, AirPrint and PDF. Your first completed output is included; Pro is a one-time purchase.</p><a class="store" href="https://apps.apple.com/app/id6808903369?ct=guide-{slug}&amp;mt=8" aria-label="Download Photo Print on the App Store"><img src="assets/app-store-badge.svg" width="168" height="56" alt="Download on the App Store"></a></aside>'
 esc=html.escape
 out=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(description,quote=True)}"><link rel="canonical" href="{url}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="article"><meta property="og:title" content="{esc(title,quote=True)}"><meta property="og:description" content="{esc(description,quote=True)}"><meta property="og:url" content="{url}"><meta name="apple-itunes-app" content="app-id=6808903369"><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="apple-touch-icon" href="assets/app-icon.png"><link rel="stylesheet" href="assets/style.css?v=20261005"><script type="application/ld+json">{json.dumps(data,ensure_ascii=False)}</script></head><body><a class="skip" href="#main">Skip to content</a><div class="wrap">{header}<main id="main"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Photo Print</a><span aria-hidden="true">/</span><a href="guides.html">Printing guides</a></nav><h1>{esc(title)}</h1><p class="updated">By <a href="about.html">Mohamed Elatabany</a> · Updated 3 October 2026</p>{body}{cta}</main>{footer}</div>{script}</body></html>'''
 (ROOT/(slug+'.html')).write_text(out)
 return {'@type':kind,'headline':title,'url':url,'description':description}
related='<p><a href="print-printer-test-sheet.html">Check scaling with a free printer test sheet</a></p><h2>Next steps</h2><ul><li><a href="photo-size-calculator.html">Convert photo sizes and calculate pixel targets</a></li><li><a href="photo-printed-wrong-size.html">Fix prints that come out at the wrong size</a></li><li><a href="guides.html">Browse all printing guides</a></li></ul>'
guides=[]
guides.append(page('print-35x45-mm-photos-iphone','Print 35 × 45 mm photos from iPhone','Make a 35 × 45 mm photo sheet on iPhone. Check the exact size, cropping, paper margins and PDF scaling before you trim.', '''
<p class="answer">A 35 × 45 mm photo is <strong>3.5 × 4.5 cm</strong>, or about <strong>1.378 × 1.772 inches</strong>. In Photo Print, choose the 35 × 45 mm preset, arrange copies on your loaded paper size, and print with AirPrint or export a PDF at 100% scale.</p>
<div class="card"><strong>The dimensions are only one requirement.</strong><p>If this is for a passport, visa or identity document, check the issuing authority’s current requirements before taking or editing the portrait. Size alone does not establish eligibility. Photo Print helps with sizing and placement; it does not certify compliance.</p></div>
<h2>Make the sheet</h2><ol><li>Start a layout and add your portrait from the photo library.</li><li>Select <strong>35 × 45 mm</strong>. Enter millimetres directly if using a custom size; do not round to 1.4 × 1.8 inches.</li><li>Use Fill for a portrait covering the rectangle. Open the crop editor and position the face. The head-size guide is a positioning aid; verify it against your application’s rules.</li><li>Add the copies you need. Choose A4, US Letter or 4 × 6 to match the paper in your printer.</li><li>Leave space for printer margins and trimming. Look for any unplaced photos in the preview.</li><li>Print or save the PDF. For a PDF, choose Actual size or 100%, then measure one photo with a ruler.</li></ol>
<h2>What resolution do I need?</h2><p>At 300 pixels per printed inch, the target is approximately <strong>414 × 532 pixels after cropping</strong>, rounded up. This is a print-resolution example, not an official document requirement. A larger original gives you more room to crop; increasing pixel dimensions later cannot recover missing detail.</p>
<h2>How many fit on a 4 × 6 sheet?</h2><p>A simple portrait grid can fit eight: four 35 mm columns across the 152.4 mm side and two 45 mm rows across the 101.6 mm side. With 2 mm between photos, that grid measures 146 × 92 mm, before page margins. Your printer may need more edge clearance, so use the preview rather than assuming every printer will accept that layout.</p>
<h2>Why is my printed photo too small?</h2><p>Automatic PDF scaling can shrink the entire sheet. Correct the print settings rather than compensating by changing a required 35 × 45 mm size in the app. If part of the photo is cut off at 100%, move it away from the sheet’s unprintable edges.</p>'''+related))
guides.append(page('print-wallet-photos-iphone','Print wallet-size photos from iPhone','Print 2 × 3 inch wallet photos or a custom frame size from iPhone. Learn Fit versus Fill, sheet layout, pixel targets and trimming.', '''
<p class="answer">Photo Print’s wallet preset is <strong>2 × 3 inches (50.8 × 76.2 mm)</strong>. Choose it for small prints, or enter the exact dimensions of your frame or wallet pocket. “Wallet size” is not a single universal measurement.</p>
<h2>Measure before choosing a preset</h2><p>Measure the space where the photo will sit, including any overlap beneath a frame mount. A 2 × 3 inch print and a 2.5 × 3.5 inch print are different sizes. For a gift or collage, pick the dimensions deliberately instead of relying on the word “wallet.”</p>
<h2>Fit or Fill?</h2><div class="table-wrap"><table><caption>Choose based on what matters in the photo</caption><thead><tr><th scope="col">Mode</th><th scope="col">Result</th><th scope="col">Use it when</th></tr></thead><tbody><tr><th scope="row">Fit</th><td>Preserves the whole image; blank space can remain inside the target rectangle.</td><td>You need to keep everyone or an important detail.</td></tr><tr><th scope="row">Fill</th><td>Covers the rectangle; some of the original image may be cropped.</td><td>You want an edge-to-edge photo and can adjust the crop.</td></tr></tbody></table></div>
<h2>Print a wallet photo sheet</h2><ol><li>Start a layout, add photos and select the 2 × 3 in preset.</li><li>Choose Fit or Fill for each image. Check faces, hands and text near the crop edges.</li><li>Select your actual paper: 4 × 6, A4 or US Letter.</li><li>Add copies or different photos, then adjust margins, spacing and optional cut guides.</li><li>Review the sheet. Photos that do not fit are reported rather than silently shrunk.</li><li>Print with AirPrint or export a PDF. Use Actual size / 100% when printing the PDF.</li><li>Measure one photo, then trim the sheet.</li></ol>
<h2>Four wallet photos on 4 × 6 paper?</h2><p>Four 2 × 3 inch rectangles exactly fill a 4 × 6 inch sheet in a two-by-two grid. There is no room for gaps or page margins. A printer that cannot print to the edges may clip or scale that arrangement; leave clearance or choose a larger sheet if exact dimensions matter.</p>
<h2>Keep small prints sharp</h2><p>A 2 × 3 inch image needs 600 × 900 visible pixels for 300 PPI. A heavily zoomed crop uses fewer of the original pixels. Check the app’s quality indicator after adjusting the crop, and use the original photo rather than a compressed messaging copy when possible.</p>'''+related))
guides.append(page('print-photo-pdf-actual-size','Print a photo PDF at actual size: home or print shop','Export a photo sheet from iPhone and print it at 100% without unwanted scaling. Includes a print-shop checklist and ruler verification.', f'''
<p class="answer">To keep photo dimensions unchanged, print the exported PDF on matching paper using <strong>Actual size</strong> or <strong>100% scale</strong>. “Fit” changes the page size to suit the printable area and can change every photo’s dimensions.</p>
<h2>Prepare the PDF on iPhone</h2><ol><li>Arrange photos in Photo Print at the dimensions you need.</li><li>Choose the paper size the printer or shop will use. A4 and US Letter are different page sizes.</li><li>Leave sufficient page margins. The PDF can contain correct measurements and still be clipped by a printer’s unprintable edges.</li><li>Save or share the PDF from the output screen. Send that file to the shop, rather than a screenshot of the preview.</li></ol>
<h2>The print settings that matter</h2><p>In Adobe Acrobat, select Size under Page Sizing &amp; Handling and choose Actual size. Adobe explains that this prints without scaling; content that does not fit can be cropped. See <a href="{ADOBE}">Adobe’s page-size printing instructions</a>.</p>
<div class="table-wrap"><table><caption>Settings to check before the first sheet</caption><thead><tr><th scope="col">Setting</th><th scope="col">Choose</th><th scope="col">Why</th></tr></thead><tbody><tr><th scope="row">Paper</th><td>Same size as the PDF</td><td>Prevents a page-size mismatch.</td></tr><tr><th scope="row">Scale</th><td>Actual size / 100%</td><td>Preserves physical dimensions.</td></tr><tr><th scope="row">Pages per sheet</th><td>One PDF page per sheet</td><td>The PDF already contains your photo layout.</td></tr><tr><th scope="row">Borderless expansion</th><td>Check printer-specific settings</td><td>Some printers enlarge to cover the edges.</td></tr></tbody></table></div>
<h2>A checklist to send to your print shop</h2><div class="card"><p>Please print this PDF on the paper size specified in the file, at actual size / 100%, one PDF page per sheet. Please do not fit, shrink or enlarge the page. Print one test sheet first so I can measure the photo dimensions before the full run.</p></div>
<h2>Measure the first sheet</h2><p>For a 2 × 2 inch photo, check both sides: each should measure 50.8 mm. If it measures 48 mm, the scale is about 94.5% (48 ÷ 50.8 × 100). Correct the print settings before printing the rest; changing the layout to compensate can hide the underlying problem.</p>
<h2>Can I print without AirPrint?</h2><p>Yes. PDF export lets you print from a computer or a shop. Direct printing from Photo Print uses AirPrint. Exporting preserves the layout, but the final printer settings and paper still determine the physical result.</p>'''+related))
guides.append(page('photo-print-resolution-ppi','Photo print resolution: pixels, PPI and cropping','Calculate pixels for 4 × 6, 2 × 2 and 35 × 45 mm prints. Understand print quality, cropping, and the difference between PPI and printer DPI.', '''
<p class="answer">Print resolution is the number of image pixels per printed inch: <strong>PPI = visible pixels ÷ printed inches</strong>. For a 4 × 6 inch print at 300 PPI, use at least 1200 × 1800 pixels after the crop. 300 PPI is a useful target, not a guarantee of a good print.</p>
<h2>Pixel targets for common photo sizes</h2><div class="table-wrap"><table><caption>300 PPI examples; fractional pixel targets rounded up</caption><thead><tr><th scope="col">Printed dimensions</th><th scope="col">Visible pixel target</th></tr></thead><tbody><tr><th scope="row">1 × 1 in</th><td>300 × 300</td></tr><tr><th scope="row">2 × 2 in</th><td>600 × 600</td></tr><tr><th scope="row">2 × 3 in</th><td>600 × 900</td></tr><tr><th scope="row">4 × 6 in</th><td>1200 × 1800</td></tr><tr><th scope="row">5 × 7 in</th><td>1500 × 2100</td></tr><tr><th scope="row">35 × 45 mm</th><td>414 × 532</td></tr></tbody></table></div>
<h2>Why cropping lowers resolution</h2><p>Only the part of the source image that reaches the page counts. If a 1200 × 1800 image fills a 4 × 6 print, it supplies 300 PPI. If you zoom until only a 600 × 900 region remains visible at that same size, the print has 150 PPI. The original file’s total pixel count can therefore overstate the quality of a tightly cropped print.</p>
<h2>How Photo Print describes quality</h2><p>The app calculates PPI from the visible crop and the physical area the image occupies. Its labels are:</p><ul><li><strong>Excellent:</strong> 300 PPI or more.</li><li><strong>Good:</strong> 200 to below 300 PPI.</li><li><strong>Fair:</strong> 150 to below 200 PPI.</li><li><strong>Low:</strong> below 150 PPI.</li></ul><p>These are the app’s quality bands, not a passport authority’s rules. Focus, motion blur, lighting, compression, ink and paper affect the result too. A blurry original remains blurry even if it has many pixels.</p>
<h2>PPI is different from printer DPI</h2><p>PPI describes image pixels across the print. DPI describes the printer’s output dots. A printer’s advertised DPI does not replace the need for enough image detail. Changing a file’s resolution label without adding real detail does not make the original photo sharper.</p>
<h2>If the quality warning appears</h2><ol><li>Try the original camera photo rather than a screenshot or messaging copy.</li><li>Reduce crop zoom if that preserves the composition.</li><li>Choose a smaller print size if your use allows it.</li><li>Print one test and assess it at the distance it will be viewed.</li></ol><p>Use the <a href="photo-size-calculator.html">photo size calculator</a> for pixel targets. It does not inspect your actual photo or validate identity-document rules.</p>'''+related))
guides.append(page('airprint-photo-printing-troubleshooting','AirPrint photo printing: missing printer, margins and paper','Troubleshoot iPhone photo printing: AirPrint discovery, loaded paper, clipped edges and PDF fallback without changing your photo dimensions.', f'''
<p class="answer">If an AirPrint printer does not appear, confirm that it supports AirPrint and that your iPhone or iPad can reach it on the same Wi-Fi network. If the printer appears but the photo is clipped or the wrong size, check paper selection, margins and scaling separately.</p>
<h2>No AirPrint printer found</h2><ol><li>Check the printer model’s AirPrint support with its manufacturer.</li><li>Connect the phone and printer to the same Wi-Fi network. A printer can also connect to that network by Ethernet.</li><li>Wake the printer and check its network connection. Guest networks or network isolation can prevent devices from discovering one another; ask your network administrator if appropriate.</li><li>Open Photo Print’s output screen, choose Print and select the printer in the system print panel.</li></ol><p><a href="{APPLE}">Apple’s AirPrint instructions</a> explain compatibility and network requirements. A USB-only connection to your computer does not automatically make a printer discoverable through AirPrint.</p>
<h2>The print is on the wrong paper</h2><p>Set the layout paper to the size loaded in the printer, then inspect the paper options shown after selecting that printer. A4 is 210 × 297 mm; US Letter is 215.9 × 279.4 mm; 4 × 6 inch paper is 101.6 × 152.4 mm. Similar-looking settings are not interchangeable when photo dimensions matter.</p>
<h2>The edges are missing</h2><p>Many printers cannot print across the entire sheet. A correctly sized photo touching the edge may be clipped. Increase page margins, reduce spacing or copies, or choose a larger sheet. Keep the photo dimensions fixed. Photo Print reports photos that do not fit its configured layout instead of shrinking them.</p>
<h2>Borderless printing looks enlarged</h2><p>Some printer settings expand an image to cover the sheet edges. Look for borderless expansion or enlargement controls in the printer’s software, and measure one print. If the iPhone print panel does not expose enough control, export the PDF and print from a computer where those settings are available.</p>
<h2>A useful fallback</h2><p>Save the photo sheet as a PDF, transfer it to a computer or print shop, and choose Actual size / 100% on matching paper. See the <a href="print-photo-pdf-actual-size.html">PDF print checklist</a>. A PDF keeps your layout portable; it cannot make unsupported hardware AirPrint-compatible.</p>
<h2>What to send support</h2><p>Include the printer model, loaded paper size, selected layout size and the measured printed dimensions. Describe whether the problem is discovery, clipping or scaling. You can share a non-sensitive screenshot of the layout and print options; avoid sending identity documents or personal portraits unless necessary.</p><p><a href="support.html">Contact Photo Print support</a>.</p>'''+related))
rows=[('1 × 1 in',25.4,25.4),('2 × 2 in',50.8,50.8),('2 × 3 in',50.8,76.2),('4 × 6 in',101.6,152.4),('5 × 7 in',127,177.8),('35 × 45 mm',35,45),('33 × 48 mm',33,48),('50 × 70 mm',50,70)]
import math
tr=''.join(f'<tr><th scope="row">{name}</th><td>{w:g} × {h:g}</td><td>{w/25.4:.3f} × {h/25.4:.3f}</td><td>{math.ceil(round(w/25.4*300,10))} × {math.ceil(round(h/25.4*300,10))}</td></tr>' for name,w,h in rows)
calculator=page('photo-size-calculator','Photo size calculator: inches, mm and print pixels','Convert photo dimensions between inches, centimetres and millimetres and calculate pixel targets. Includes a common-size chart and print-quality examples.',f'''
<p class="answer">One inch is exactly <strong>25.4 mm</strong>. Convert millimetres to inches by dividing by 25.4. To calculate a print-resolution target, multiply each dimension in inches by your chosen PPI.</p>
<section class="calculator card" aria-labelledby="calc-heading"><h2 id="calc-heading">Calculate your photo size</h2><form id="size-form"><div class="calc-fields"><label>Width<input id="size-width" type="number" min="0.01" max="10000" step="any" value="2" required inputmode="decimal"></label><label>Height<input id="size-height" type="number" min="0.01" max="10000" step="any" value="2" required inputmode="decimal"></label><label>Units<select id="size-unit"><option value="in">Inches</option><option value="mm">Millimetres</option><option value="cm">Centimetres</option></select></label><label>Target PPI<select id="size-ppi"><option value="300">300 PPI</option><option value="200">200 PPI</option><option value="150">150 PPI</option></select></label></div><button type="submit">Calculate</button></form><output id="size-result" for="size-width size-height size-unit size-ppi" aria-live="polite"><strong>2 × 2 in = 50.8 × 50.8 mm = 5.08 × 5.08 cm</strong><br>At 300 PPI: at least 600 × 600 visible pixels.</output><p class="fine">Calculated in your browser. No photo upload. Pixel targets describe resolution after cropping, not identity-document compliance.</p><noscript><p>The calculator needs JavaScript. The conversion formulas and size chart below work without it.</p></noscript></section>
<h2>Common photo sizes</h2><div class="table-wrap"><table><caption>Dimensions and 300 PPI targets; decimal inches shown rounded to three places</caption><thead><tr><th scope="col">Size</th><th scope="col">Millimetres</th><th scope="col">Inches</th><th scope="col">Pixels at 300 PPI</th></tr></thead><tbody>{tr}</tbody></table></div>
<h2>Use the original units for exact printing</h2><p>The table rounds decimal inches for readability. For a 35 × 45 mm print, enter 35 and 45 in millimetres in the app instead of entering rounded inch values. For a 2 × 2 inch photo, enter inches: 50 × 50 mm is a smaller rectangle.</p>
<h2>How to calculate print pixels</h2><p>For a 4 × 6 inch print at 300 PPI, multiply 4 × 300 and 6 × 300: 1200 × 1800 pixels. For 35 × 45 mm, divide by 25.4 first and multiply by 300: approximately 413.39 × 531.50, rounded up to 414 × 532 pixels.</p>
<h2>Pixel dimensions do not decide the printed size</h2><p>The same file can be printed at several physical sizes. Its PPI changes with the chosen dimensions and crop. Photo Print lets you set physical dimensions directly and check quality in the finished layout. See <a href="photo-print-resolution-ppi.html">pixels, PPI and cropping</a>.</p>'''+related,kind='WebPage',script='<script src="assets/size-calculator.js" defer></script>')
# Add the new distinct questions and utility to the existing guide index.
p=ROOT/'guides.html';s=p.read_text();s=s.replace('Updated 1 October 2026','Updated 3 October 2026')
a=s.index('<div class="card">');b=s.index('<p>The guides use',a)
original={'print-printer-test-sheet.html','print-passport-photos-at-home.html','print-4x6-photo-exact-size-iphone.html','print-multiple-photos-on-one-page.html','photo-printed-wrong-size.html','print-2x2-photos-iphone.html','print-1x1-id-photos-iphone.html'}
existing=[card for card in re.findall(r'<div class="card">.*?</div>',s[a:b],re.S) if any('href="'+name+'"' in card for name in original)]
new=''.join(f'<div class="card"><h2><a href="{g["url"].removeprefix(BASE)}">{g["headline"]}</a></h2><p>{g["description"]}</p></div>' for g in guides)
s=s[:a]+'<div class="card"><p class="eyebrow">Start with your measurements</p><h2><a href="photo-size-calculator.html">Photo size &amp; resolution calculator</a></h2><p>Convert inches, centimetres and millimetres. Find pixel targets and common print sizes.</p></div><h2>Choose a printing task</h2>'+''.join(existing)+'<h2>Paper, quality &amp; printer settings</h2>'+new+s[b:]
m=re.search(r'<script type="application/ld\+json">(.*?)</script>',s,re.S);d=json.loads(m[1]);new_urls={g['url'] for g in guides+[calculator]};d['hasPart']=[g for g in d['hasPart'] if g['url'] not in new_urls]+guides+[calculator];s=s[:m.start(1)]+json.dumps(d,ensure_ascii=False)+s[m.end(1):];p.write_text(s)
